ALTER SEQUENCE brands_brand_id_seq start WITH 7;
ALTER sequence brands_brand_id_seq restart;
ALTER SEQUENCE category_id_seq start WITH 12;
ALTER sequence category_id_seq restart;
ALTER SEQUENCE user_id_seq start WITH 11;
ALTER sequence user_id_seq restart;
ALTER SEQUENCE instrument_id_seq start WITH 28;
ALTER sequence instrument_id_seq restart;
ALTER SEQUENCE order_id_seq start WITH 10;
ALTER sequence order_id_seq restart;
ALTER SEQUENCE order_item_id_seq start WITH 20;
ALTER sequence order_item_id_seq restart;
