version: "3.2"

volumes:
  storage-let-me-rent:
    driver: local
  minio_data:
    driver: local

services:
  postgres:
    image: postgres:12
    container_name: storage-let-me-rent
    domainname: storage
    volumes:
      - type: volume
        source: storage-let-me-rent
        target: /var/lib/postgresql/dataConfig
    environment:
      POSTGRES_DB: letmerent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
    ports:
      - 5435:5432

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  minio:
    image: bitnami/minio:latest
    container_name: minio_data
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio-password
      - MINIO_DEFAULT_BUCKETS=let-me-rent:public