server:
  port: 8890
  servlet:
    context-path: /let-me-rent

spring:
  application:
    name: let-me-rent
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/letmerent
    username: postgres
    password: postgrespass
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jackson:
    default-property-inclusion: NON_NULL
  main:
    allow-bean-definition-overriding: true

swagger:
  title: CoreService
  description: API для работы с let-me-rent
  contact:
    mail: let-me-rent@gmail.com
    command: ДайПогонять
    url: https://gb.ru/

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

utils:
  cart:
    prefix: LET_ME_RENT_