server:
  port: 8888

spring:
  application:
    name: let-me-rent
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/letmerent
    username: postgres
    password: postgrespass
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml